### ISSUE TITLE
change Subtitles Background color & font colors

### ISSUE THREAD

**Issue by itshaadi** [sanjevirau/gsubs#5]
in some videos when more than one language is spoken most likely there is a Hardsub, so a common way to show your subtitle on top of a Hardsub is tho change the background and font color (yellow on black).

and although most media players can change subtitles background color & font color. but in some cases like on a TV (or devices that support DLNA) you can't do that. so this is a useful functionality to have.

**Comment by sanjevirau** [comment]
Hey @itshaadi,
Thanks a lot for the new feature idea. I would like to look into it. gSubs however finds the subtitle in the databases of OpenSubtitle and SubDB and download the srt files. Due to that, for now gSubs don't edit the srt files. The subtitles files are as it is. I hope in future maybe gSubs can have control of editing the srt files to customize the font and colors as you wished.

Thank you.

**Comment by sanjevirau** [comment]
Hey @itshaadi,
After some research, I've been told that it's the best to change the color and fonts in the player. For your case, you need to use some other subtitle editors to achieve the result for now.

Thank you.
