### ISSUE TITLE
A few Suggestions

### ISSUE THREAD

**Issue by Vastrix** [sanjevirau/gsubs#6]
First of all, waw!
Looks amazingly smooth, the world could use more sexy looking programs ;)

A few suggestions tho:

- **Add an *expert*(?) option to always show all found subtitles**
Some of us like the additional control \o/  

- **Allow for window resizing**
*When the "multiple subtitle" screen pops up, it'd be cool if we could read the entire filename ;)*

- **Ability to Parse folders**
*It'd be cool if we could drag a folder onto it, into which the program will look for video files and then ofc parse them*
  
  
As a somewhat bigger feature I'd like to suggest **auto-renaming**.
The ability for the app to match the video to known databases to retrieve the correct name (through the info from the [hashlookup from opensubs](http://trac.opensubtitles.org/projects/opensubtitles/wiki/XMLRPC#CheckMovieHash)**?**)
  
Regardless, very nice job! :)

**Comment by sanjevirau** [comment]
Hey @Vastrix, 
Thanks a lot for the compliments and suggestions. As for the suggestions, I think the expert options is possible as I can implement gSubs to show all the subtitles according to the filename. 

The windows resizing however, I don't think so it will be possible due to the fact that gSubs user interface is actually made for not re sizable. However, there is a workaround for this, I'm implementing to  animate the filenames when it's being hovered by mouse.

The ability to add folder is also under implementation. Can I know more in detail on what you actually meant by the **auto-renaming**?

Thank you.

**Comment by Vastrix** [comment]
Awesome!  
  
What I meant with auto renaming:  
I'm assuming you're using opensub's `SearchByHash` function to find the right sub for each video?  
Opensubs also has [a function](http://trac.opensubtitles.org/projects/opensubtitles/wiki/XMLRPC#CheckMovieHash) that returns the imdbid and __the correct video name__! Awesome right? \o/  
  
The Idea is that after/while/before searching for a sub, you also run this function, get the correct name and rename the video file (and sub) to said name :)

**Comment by sanjevirau** [comment]
Hey @Vastrix,
Great, I have understood it now. The implementations needed are added in the todo list in the project and will be implemented in near future.

Thank you.

**Comment by Vastrix** [comment]
no, Thank **you** ;)
